title: EFI
description: Exploring Tools for Effective Advocacy
email: hubert.thieriot@gmail.com
logo: "/assets/images/equalizer.png"
float_logo: false
cover: "/assets/images/soulages.jpg"
name: Hubert Thieriot
author: Hubert Thieriot
author_image: "/assets/images/author.jpg"
paginate: 5
paginate_path: "/page:num"
url: "https://hubert-thieriot.github.io"
baseurl: "/efi-corpus"
twitter_handle: "@hubert_thieriot"
remote_theme: dirkfabisch/mediator

markdown: kramdown
permalink: pretty
encoding: "utf-8"

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-remote-theme

social:
  - icon: github
    url: https://github.com/hubert-thieriot
    desc: GitHub
    share_url: https://github.com/hubert-thieriot
    share_title: "Check out this post: "
    share_link: ""
  - icon: linkedin
    url: https://www.linkedin.com/in/hubertthieriot/
    desc: LinkedIn
    share_url: https://www.linkedin.com/sharing/share-offsite/?url=
    share_title: ""
    share_link: ""

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Hubert Thieriot"
